export const postCardData = [
    {
      id: 1,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/01.png",
      isPositionTop: false,
      category: "Tourism",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "June 6, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 2,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/02.png",
      isPositionTop: false,
      category: "sport",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "June 5, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 3,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/03.png",
      isPositionTop: true,
      category: "fashion",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "June 4, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 4,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/04.png",
      isPositionTop: false,
      category: "clothes",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "June 3, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 5,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/05.png",
      isPositionTop: true,
      category: "clothes",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "June 2, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 6,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/06.png",
      isPositionTop: false,
      category: "fashion",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "June 1, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 7,
      cardSize: "big",
      imageUrl: "/img/blog/postcard/07.png",
      isPositionTop: true,
      category: "Summer",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "May 30, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 8,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/08.png",
      isPositionTop: false,
      category: "Autumn",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "May 25, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 9,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/09.png",
      isPositionTop: true,
      category: "clothes",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "May 22, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 10,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/10.png",
      isPositionTop: false,
      category: "summer",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "May 19, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
    {
      id: 11,
      cardSize: "medium",
      imageUrl: "/img/blog/postcard/11.png",
      isPositionTop: false,
      category: "summer",
      title: "One of Saturn’s largest rings may be newer than anyone",
      date: "May 16, 2019",
      author: "Rickie Baroch",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem",
      liked: false,
    },
];